### ISSUE TITLE
get_fields_at_point doesn't evaluate the fields at a point

### ISSUE THREAD

**Issue by TomGoffrey** [ExCALIBUR-NEPTUNE/minepoch#25]
The subroutine `get_fields_at_point` doesn't evaluate the fields at a given point. This is demonstrated by the unit test added on the branch tom/field_calculation_test. The results returned from this subroutine still need to multiplied by the omnipresent `fac` variable.

This is clearly a relic of previous optimisation (of the particle push), but as it stands the current implementation is dangerous. It's not unreasonable to expect `get_fields_at_point` to return the value of the fields, at a point.

I propose to fix this, by applying the `fac` factor in the routine itself. Clearly there is a performance hit (6 extra multiplications for each particle), but I think that performance hit is much less than that of adding the subroutine in the first place.

@benmcmillanwarwick Any objections?

I'd also like to add the field evaluation test to our CI testing.

**Comment by benmcmillanwarwick** [comment]
No, agreed that 'fac' should be in the get_fields_at_point routine.

Agree that the performance hit is small, and priority is making the interface sensible.
